/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-05-29 04:22:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');\r\n");
      out.write("section {\r\n");
      out.write("    padding: 1% ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#footer {\r\n");
      out.write("    background: #D7DBDD   !important;\r\n");
      out.write("}\r\n");
      out.write("#footer h5{\r\n");
      out.write("                padding-left: 10px;\r\n");
      out.write("    border-left: 3px solid black;\r\n");
      out.write("    padding-bottom:3px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#footer ul.social li{\r\n");
      out.write("                padding: 3px 0;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.social li a i {\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("                font-size:25px;\r\n");
      out.write("                -webkit-transition: .5s all ease;\r\n");
      out.write("                -moz-transition: .5s all ease;\r\n");
      out.write("                transition: .5s all ease;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.social li:hover a i {\r\n");
      out.write("               \r\n");
      out.write("                margin-top:0px;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.social li a,\r\n");
      out.write("#footer ul.quick-links li a{\r\n");
      out.write("                color:grey;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.social li a:hover{\r\n");
      out.write("                color:black;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.quick-links li{\r\n");
      out.write("                padding: 3px 0;\r\n");
      out.write("                -webkit-transition: .5s all ease;\r\n");
      out.write("                -moz-transition: .5s all ease;\r\n");
      out.write("                transition: .5s all ease;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.quick-links li:hover{\r\n");
      out.write("                padding: 3px 0;\r\n");
      out.write("                margin-left:5px;\r\n");
      out.write("                font-weight:700;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.quick-links li a i{\r\n");
      out.write("                margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("#footer ul.quick-links li:hover a i {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width:767px){\r\n");
      out.write("                #footer h5 {\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("    border-left: transparent;\r\n");
      out.write("    padding-bottom: 30px;\r\n");
      out.write("    margin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("                <section id=\"footer\">\r\n");
      out.write("                                <div class=\"container\">\r\n");
      out.write("                                                <div class=\"row text-center text-xs-center text-sm-left text-md-left\">\r\n");
      out.write("                                                                <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                                                                <h5>Popular Locations</h5>\r\n");
      out.write("                                                                                <ul class=\"list-unstyled quick-links\">\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>Chennai</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>Mumbai</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>Pune</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i> Banglore</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>Hyderabad</a></li>\r\n");
      out.write("                                                                                </ul>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                                                                <h5>AboutUs</h5>\r\n");
      out.write("                                                                                <ul class=\"list-unstyled quick-links\">\r\n");
      out.write("                                                                                               <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>AboutOlxGroup</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>Carrers</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>ContactUs</a></li>\r\n");
      out.write("                                                                                                \r\n");
      out.write("                                                                                </ul>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"col-xs-12 col-sm-4 col-md-4\">\r\n");
      out.write("                                                                                <h5>Olx</h5>\r\n");
      out.write("                                                                                <ul class=\"list-unstyled quick-links\">\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>Help</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>SiteMap</a></li>\r\n");
      out.write("                                                                                                <li><a href=\"javascript:void();\"><i class=\"fa fa-angle-double-right\"></i>Legacy&Information</a></li>\r\n");
      out.write("                                                                                                \r\n");
      out.write("                                                                                </ul>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                                <div class=\"col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5\">\r\n");
      out.write("                                                                                <ul class=\"list-unstyled list-inline social text-center\">\r\n");
      out.write("                                                                                                <li class=\"list-inline-item\"><a href=\"javascript:void();\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                                                                                                <li class=\"list-inline-item\"><a href=\"javascript:void();\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                                                                                               <li class=\"list-inline-item\"><a href=\"javascript:void();\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("                                                                                                <li class=\"list-inline-item\"><a href=\"javascript:void();\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                                                                                                <li class=\"list-inline-item\"><a href=\"javascript:void();\" target=\"_blank\"><i class=\"fa fa-envelope\"></i></a></li>\r\n");
      out.write("                                                                                </ul>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                </hr>\r\n");
      out.write("                                                </div>   \r\n");
      out.write("                                                 \r\n");
      out.write("                </section>\r\n");
      out.write("                <!-- ./Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
