/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-05-31 04:55:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bootstrap Example</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/* Remove the navbar's default margin-bottom and rounded borders */\r\n");
      out.write(".navbar {\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tborder-radius: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a gray background color and some padding to the footer */\r\n");
      out.write("footer {\r\n");
      out.write("\tbackground-color: #f2f2f2;\r\n");
      out.write("\tpadding: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner img {\r\n");
      out.write("\twidth: 100%; /* Set width to 100% */\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmin-height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner-addon {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* style icon */\r\n");
      out.write(".inner-addon .glyphicon {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button used to open the contact form - fixed at the bottom of the page */\r\n");
      out.write(".open-button {\r\n");
      out.write("\tbackground-color: #555;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 16px 20px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 23px;\r\n");
      out.write("\tcenter: 28px;\r\n");
      out.write("\twidth: 280px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The popup form - hidden by default */\r\n");
      out.write(".form-popup {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tcenter: 15px;\r\n");
      out.write("\tborder: 3px solid #f1f1f1;\r\n");
      out.write("\tz-index: 9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add styles to the form container */\r\n");
      out.write(".form-container {\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write(".form-container input[type=text], .form-container input[type=password] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\tmargin: 5px 0 22px 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* When the inputs get focus, do something */\r\n");
      out.write(".form-container input[type=text]:focus, .form-container input[type=password]:focus\r\n");
      out.write("\t{\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit/login button */\r\n");
      out.write(".form-container .btn {\r\n");
      out.write("\t\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 16px 20px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a red background color to the cancel button */\r\n");
      out.write(".form-container .cancel {\r\n");
      out.write("\tbackground-color: #2980B9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add some hover effects to buttons */\r\n");
      out.write(".form-container .btn:hover, .open-button:hover {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("/* align icon */\r\n");
      out.write(".left-addon .glyphicon {\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right-addon .glyphicon {\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* add padding  */\r\n");
      out.write(".left-addon input {\r\n");
      out.write("\tpadding-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right-addon input {\r\n");
      out.write("\tpadding-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("/* Hide the carousel text when the screen is less than 600 pixels wide */\r\n");
      out.write("@media ( max-width : 600px) {\r\n");
      out.write("\t.carousel-caption {\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".log {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-dialog {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".md1 {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\"></div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div id=\"myCarousel\" style=\"width: 1900px; min-height: 200px\"\r\n");
      out.write("\t\tclass=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t<!-- Indicators -->\r\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Wrapper for slides -->\r\n");
      out.write("\t\t<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t<img src=\"images/car1.jpg\" alt=\"Image\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 60%; height: 400px\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h3>Sell $</h3>\r\n");
      out.write("\t\t\t\t\t<p>old mercedes ben</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"images/bike1.jpg\" alt=\"Image\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 60%; height: 400px\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h3>More Sell $</h3>\r\n");
      out.write("\t\t\t\t\t<p>yamaha RX100</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"images/swing.jpg\" alt=\"Image\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 60%; height: 400px\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h3>More Sell $</h3>\r\n");
      out.write("\t\t\t\t\t<p>wooden swing</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"images/laptops.jpg\" alt=\"Image\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 60%; height: 400px\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<h3>More Sell $</h3>\r\n");
      out.write("\t\t\t\t\t<p>laptop</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Left and right controls -->\r\n");
      out.write("\t\t<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("\t\t\tdata-slide=\"prev\"> <span class=\"glyphicon glyphicon-chevron-left\"\r\n");
      out.write("\t\t\taria-hidden=\"true\"></span> <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t</a> <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("\t\t\tdata-slide=\"next\"> <span\r\n");
      out.write("\t\t\tclass=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 75%; height: 250px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\" style=\"width: 70%\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/olx_resale/fetch\">View Details</a>\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 75%; height: 250px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/bike1.jpg\" style=\"width: 70%\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 75%; height: 250px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/swing.jpg\" style=\"width: 70%\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 75%; height: 250px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/laptops.jpg\" style=\"width: 70%\" alt=\"Image\">\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jumbotron\" style=\"background-color: #D7DBDD ; color: black\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tPOPULAR SEARCHES<small><br> Mobile<br> Cars<br>\r\n");
      out.write("\t\t\t\t\t\t\tBikes</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tTRENDING<small><br> Mobile<br> Cars<br>\r\n");
      out.write("\t\t\t\t\t\t\tBikes</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tABOUT US<small><br> About OLX Group<br> Careers<br>Contact\r\n");
      out.write("\t\t\t\t\t\t\tUs</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tOLX<small><br> Legal and Privacy information<br>Site\r\n");
      out.write("\t\t\t\t\t\t\tMap<br>Help</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
