/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-06-07 06:28:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Myads_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bootstrap Example</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<!-- <h2 style=\"text-align:center\">Your ads are empty</h2><br>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-sm-1\"></div>\r\n");
      out.write("<div class=\"col-sm-9\">\r\n");
      out.write("  <img src=\"images/vadinew.jpg\" ></div>\r\n");
      out.write("  <div class=\"col-sm-2\"></div></div></div> -->\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 85%; height: 650px\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/car1.jpg\"  alt=\"Image\" style=\"float:left\" width=\"350\" >\r\n");
      out.write("\t\t\t\t\t<p>Current Project</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"jumbotron\" style=\"background-color: #D7DBDD ; color: black\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tPOPULAR SEARCHES<small><br> Mobile<br> Cars<br>\r\n");
      out.write("\t\t\t\t\t\t\tBikes</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tTRENDING<small><br> Mobile<br> Cars<br>\r\n");
      out.write("\t\t\t\t\t\t\tBikes</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tABOUT US<small><br> About OLX Group<br> Careers<br>Contact\r\n");
      out.write("\t\t\t\t\t\t\tUs</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tOLX<small><br> Legal and Privacy information<br>Site\r\n");
      out.write("\t\t\t\t\t\t\tMap<br>Help</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
