/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-06-13 10:24:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class plain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validateForm(){\r\n");
      out.write("\tvar uname = document.forms[\"myForm\"][\"your-name\"].value;\r\n");
      out.write("\tvar unamecheck=/^[A-Z][a-z0-9]{3,20}$/;\r\n");
      out.write("\tvar Email = document.forms[\"myForm\"][\"your-email\"].value;\r\n");
      out.write("\t var echeck=/^[\\w._+]+@[\\w.-]+\\.[a-zA-Z]{2,4}$/;\r\n");
      out.write("\tvar phonenumber = document.forms[\"myForm\"][\"your-phone\"].value;\r\n");
      out.write("\t var pcheck =  /^([0|\\+[0-9]{1,5})?([7-9][0-9]{9})$/;\r\n");
      out.write("\t var password=document.forms[\"myForm\"][\"your-pass\"].value;\r\n");
      out.write("\t \r\n");
      out.write("    if(uname.length==0){\r\n");
      out.write("         document.getElementById(\"div1\").innerHTML=\"*username required\";\r\n");
      out.write("        document.getElementById(\"div1\").style.color=\"orange\";\r\n");
      out.write("        return false;\r\n");
      out.write("            \r\n");
      out.write("       }\r\n");
      out.write("    else if(!unamecheck.test(uname))\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div1\").innerHTML=\"First Character should be in uppercase\";\r\n");
      out.write("        document.getElementById(\"div1\").style.color=\"Red\";\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("    document.getElementById(\"div1\").innerHTML=\" \";\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    if(Email.length==0){\r\n");
      out.write("         document.getElementById(\"div2\").innerHTML=\"*Email required\";\r\n");
      out.write("        document.getElementById(\"div2\").style.color=\"orange\";\r\n");
      out.write("        return false;\r\n");
      out.write("       }\r\n");
      out.write("    \r\n");
      out.write("   else  if(!echeck.test(Email))\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div2\").innerHTML=\"Enter the valid email address using '@' and '.'\";\r\n");
      out.write("        document.getElementById(\"div2\").style.color=\"Red\";\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    else{\r\n");
      out.write("       document.getElementById(\"div2\").innerHTML=\"\";\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("     if(phonenumber.length==0){\r\n");
      out.write("         document.getElementById(\"div3\").innerHTML=\"*Contact number required\";\r\n");
      out.write("        document.getElementById(\"div3\").style.color=\"orange\";\r\n");
      out.write("        return false;\r\n");
      out.write("            \r\n");
      out.write("       }\r\n");
      out.write("  else  if(!pcheck.test(phonenumber))\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div3\").innerHTML=\"Enter 10 digit valid contact number\";\r\n");
      out.write("        document.getElementById(\"div3\").style.color=\"Red\";\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    {\r\n");
      out.write("       document.getElementById(\"div3\").innerHTML=\" \";\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("     if(password.length==0){\r\n");
      out.write("         document.getElementById(\"div4\").innerHTML=\"*Password required\";\r\n");
      out.write("        document.getElementById(\"div4\").style.color=\"orange\";\r\n");
      out.write("        return false;\r\n");
      out.write("            \r\n");
      out.write("       }\r\n");
      out.write("     else if(password.length<6|| password.length>16){\r\n");
      out.write("    \t document.getElementById(\"div4\").innerHTML=\"Enter password size between 6 and 15\";\r\n");
      out.write("         document.getElementById(\"div4\").style.color=\"Red\";\r\n");
      out.write("         return false;\r\n");
      out.write("    \t \r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("     else{\r\n");
      out.write("    \t document.getElementById(\"div4\").innerHTML=\"Password is strong \"; \r\n");
      out.write("    \t    \r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form name=\"myForm\"  action=\"/olx_resale/fetch\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label>Your Name</label> <span id=\"div1\"></span>\r\n");
      out.write("\t\t<input type=\"text\" name=\"your-name\" class=\"form-control\" placeholder=\"Enter your Name\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\"> \r\n");
      out.write("\t\t<label>Your Email</label> <span id=\"div2\"></span>\r\n");
      out.write("\t\t<input type=\"text\" name=\"your-email\" class=\"form-control\" placeholder=\"Enter your Email\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label>Your Phone</label> <span id=\"div3\"></span>\r\n");
      out.write("\t\t<input type=\"text\" name=\"your-phone\" class=\"form-control\" placeholder=\"Enter your Phone\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<label>Your pass</label> <span id=\"div4\"></span>\r\n");
      out.write("\t\t<input type=\"password\" name=\"your-pass\" class=\"form-control\" placeholder=\"Enter your Phone\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t \r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Send\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
