/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-06-04 06:03:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProductDescription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".chip {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 0 25px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tborder-radius: 25px;\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".chip img {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin: 0 10px 0 -25px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myImg {\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttransition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myImg:hover {\r\n");
      out.write("\topacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("\tdisplay: none; /* Hidden by default */\r\n");
      out.write("\tposition: fixed; /* Stay in place */\r\n");
      out.write("\tz-index: 1; /* Sit on top */\r\n");
      out.write("\tpadding-top: 100px; /* Location of the box */\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%; /* Full width */\r\n");
      out.write("\theight: 100%; /* Full height */\r\n");
      out.write("\toverflow: auto; /* Enable scroll if needed */\r\n");
      out.write("\tbackground-color: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.9); /* Black w/ opacity */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content (image) */\r\n");
      out.write(".modal-content {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmax-width: 700px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Caption of Modal Image */\r\n");
      out.write("#caption {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmax-width: 700px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: #ccc;\r\n");
      out.write("\tpadding: 10px 0;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add Animation */\r\n");
      out.write(".modal-content, #caption {\r\n");
      out.write("\t-webkit-animation-name: zoom;\r\n");
      out.write("\t-webkit-animation-duration: 0.6s;\r\n");
      out.write("\tanimation-name: zoom;\r\n");
      out.write("\tanimation-duration: 0.6s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("-webkit-keyframes zoom {\r\n");
      out.write("\tfrom {-webkit-transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\t-webkit-transform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes zoom {\r\n");
      out.write("\tfrom {transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\ttransform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Close Button */\r\n");
      out.write(".close {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 15px;\r\n");
      out.write("\tright: 35px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 40px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\ttransition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover, .close:focus {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 100% Image Width on Smaller Screens */\r\n");
      out.write("@media only screen and (max-width: 700px) {\r\n");
      out.write("\t.modal-content {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 150%; height: 450px\">\r\n");
      out.write("\t\t\t\t\t<br /> <img id=\"myImg\" src=\"images/car1.jpg\" \r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 70%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- The Modal -->\r\n");
      out.write("\t\t\t\t\t<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"close\"  >&times;</span> <img class=\"modal-content\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"img01\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"caption\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t// Get the modal\r\n");
      out.write("\t\t\t\t\t\tvar modal = document.getElementById(\"myModal\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// Get the image and insert it inside the modal - use its \"alt\" text as a caption\r\n");
      out.write("\t\t\t\t\t\tvar img = document.getElementById(\"myImg\");\r\n");
      out.write("\t\t\t\t\t\tvar modalImg = document.getElementById(\"img01\");\r\n");
      out.write("\t\t\t\t\t\tvar captionText = document.getElementById(\"caption\");\r\n");
      out.write("\t\t\t\t\t\timg.onclick = function() {\r\n");
      out.write("\t\t\t\t\t\t\tmodal.style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\tmodalImg.src = this.src;\r\n");
      out.write("\t\t\t\t\t\t\tcaptionText.innerHTML = this.alt;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// Get the <span> element that closes the modal\r\n");
      out.write("\t\t\t\t\t\tvar span = document.getElementsByClassName(\"close\")[0];\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// When the user clicks on <span> (x), close the modal\r\n");
      out.write("\t\t\t\t\t\tspan.onclick = function() {\r\n");
      out.write("\t\t\t\t\t\t\tmodal.style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 150%; height: 200px\">\r\n");
      out.write("\t\t\t\t\t<p>Details</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 150%; height: 200px\">\r\n");
      out.write("\t\t\t\t\t<p>prize</p>\r\n");
      out.write("\t\t\t\t\t                                  <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-sm-2\"></div>\r\n");
      out.write("                                  <div class=\"col-sm-2\">\r\n");
      out.write("                    <form action=\"/olx_resale/cart\"><button type=\"submit\" class=\"btn btn-primary\">Add to cart</button></form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"col-sm-2\"></div>\r\n");
      out.write("                    <div class=\"col-sm-1\">\r\n");
      out.write("                    \r\n");
      out.write("                    <form action=\"/olx_resale/buynow\"><button type=\"submit\" class=\"btn btn-primary\">Buy Now</button></form>\r\n");
      out.write("                    \r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\" style=\"width: 150%; height: 200px\">\r\n");
      out.write("\t\t\t\t\t<p>seller Description</p>\r\n");
      out.write("\t\t\t\t\t<!-- for displaying seller name -->\r\n");
      out.write("\t\t\t\t\t<div class=\"chip\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/contactimage.png\" alt=\"Person\" width=\"96\"\r\n");
      out.write("\t\t\t\t\t\t\theight=\"96\" style=\"float: left\"> John Doe\r\n");
      out.write("\t\t\t\t\t\t<h2>Phone Number</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"jumbotron\" style=\"background-color: #D7DBDD; color: black\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tPOPULAR SEARCHES<small><br> Mobile<br> Cars<br>\r\n");
      out.write("\t\t\t\t\t\t\tBikes</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tTRENDING<small><br> Mobile<br> Cars<br>\r\n");
      out.write("\t\t\t\t\t\t\tBikes</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tABOUT US<small><br> About OLX Group<br> Careers<br>Contact\r\n");
      out.write("\t\t\t\t\t\t\tUs</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 VL\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tOLX<small><br> Legal and Privacy information<br>Site\r\n");
      out.write("\t\t\t\t\t\t\tMap<br>Help</small>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
